name: Validate contribution

on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Welcome
        uses: actions/github-script@v6
        with:
          script: |
            console.log("--------------------------------------------)
            console.log(github.context.ref)
            console.log(github.context.sha)
            console.log(github.context)
            console.log(github)
            console.log("--------------------------------------------)
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you for contributing ${{ github.event.pull_request.title }}'
            })

            return true;

